<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Anotacao [
<!ELEMENT Anotation ( R+ ) >

<!ELEMENT R ( RELATION ) >
<!ATTLIST R SDID ( D1_C6_Folha.txt.seg | D2_C6_Estadao.txt.seg | D3_C6_JB.txt.seg ) #REQUIRED >
<!ATTLIST R SSENT ( 1 | 10 | 11 | 13 | 14 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 ) #REQUIRED >
<!ATTLIST R TDID ( D1_C6_Folha.txt.seg | D2_C6_Estadao.txt.seg | D3_C6_JB.txt.seg ) #REQUIRED >
<!ATTLIST R TSENT ( 1 | 10 | 11 | 12 | 14 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 ) #REQUIRED >

<!ELEMENT RELATION EMPTY >
<!ATTLIST RELATION JUDGE ( Erick | Lucía | thiago ) #REQUIRED >
<!ATTLIST RELATION TYPE ( Attribution | Elaboration | Equivalence | Indirect-speech | Overlap | Subsumption | Summary ) #REQUIRED >
] > 

<Anotation>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="1" TDID="D2_C6_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="2" TDID="D1_C6_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="1" TDID="D2_C6_Estadao.txt.seg" TSENT="5">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="2" TDID="D1_C6_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Indirect-speech" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="3" TDID="D2_C6_Estadao.txt.seg" TSENT="3">
		<RELATION TYPE="Indirect-speech" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="3" TDID="D2_C6_Estadao.txt.seg" TSENT="14">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="4" TDID="D2_C6_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Attribution" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="2" TDID="D1_C6_Folha.txt.seg" TSENT="4">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="13" TDID="D1_C6_Folha.txt.seg" TSENT="4">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="5" TDID="D2_C6_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="5" TDID="D2_C6_Estadao.txt.seg" TSENT="5">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="4" TDID="D2_C6_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="2" TDID="D2_C6_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="3" TDID="D2_C6_Estadao.txt.seg" TSENT="3">
		<RELATION TYPE="Equivalence" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="5" TDID="D2_C6_Estadao.txt.seg" TSENT="10">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="5" TDID="D2_C6_Estadao.txt.seg" TSENT="11">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="13" TDID="D1_C6_Folha.txt.seg" TSENT="5">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="11" TDID="D1_C6_Folha.txt.seg" TSENT="6">
		<RELATION TYPE="Indirect-speech" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="6" TDID="D2_C6_Estadao.txt.seg" TSENT="11">
		<RELATION TYPE="Subsumption" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="6" TDID="D2_C6_Estadao.txt.seg" TSENT="12">
		<RELATION TYPE="Subsumption" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="8" TDID="D2_C6_Estadao.txt.seg" TSENT="9">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="10" TDID="D2_C6_Estadao.txt.seg" TSENT="9">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="9" TDID="D1_C6_Folha.txt.seg" TSENT="9">
		<RELATION TYPE="Summary" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="9" TDID="D1_C6_Folha.txt.seg" TSENT="9">
		<RELATION TYPE="Indirect-speech" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="1" TDID="D3_C6_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Subsumption" JUDGE="Lucía"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="1" TDID="D3_C6_JB.txt.seg" TSENT="7">
		<RELATION TYPE="Indirect-speech" JUDGE="Lucía"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="1" TDID="D3_C6_JB.txt.seg" TSENT="7">
		<RELATION TYPE="Subsumption" JUDGE="Lucía"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="10" TDID="D1_C6_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Lucía"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="3" TDID="D1_C6_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Subsumption" JUDGE="Lucía"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="9" TDID="D1_C6_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Attribution" JUDGE="Lucía"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="2" TDID="D3_C6_JB.txt.seg" TSENT="9">
		<RELATION TYPE="Subsumption" JUDGE="Lucía"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="2" TDID="D3_C6_JB.txt.seg" TSENT="10">
		<RELATION TYPE="Subsumption" JUDGE="Lucía"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="5" TDID="D1_C6_Folha.txt.seg" TSENT="3">
		<RELATION TYPE="Indirect-speech" JUDGE="Lucía"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="5" TDID="D1_C6_Folha.txt.seg" TSENT="3">
		<RELATION TYPE="Overlap" JUDGE="Lucía"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="3" TDID="D3_C6_JB.txt.seg" TSENT="6">
		<RELATION TYPE="Subsumption" JUDGE="Lucía"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="1" TDID="D1_C6_Folha.txt.seg" TSENT="4">
		<RELATION TYPE="Indirect-speech" JUDGE="Lucía"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="1" TDID="D1_C6_Folha.txt.seg" TSENT="4">
		<RELATION TYPE="Subsumption" JUDGE="Lucía"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="4" TDID="D3_C6_JB.txt.seg" TSENT="7">
		<RELATION TYPE="Equivalence" JUDGE="Lucía"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="9" TDID="D1_C6_Folha.txt.seg" TSENT="4">
		<RELATION TYPE="Elaboration" JUDGE="Lucía"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="4" TDID="D3_C6_JB.txt.seg" TSENT="10">
		<RELATION TYPE="Overlap" JUDGE="Lucía"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="5" TDID="D3_C6_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Lucía"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="5" TDID="D1_C6_Folha.txt.seg" TSENT="5">
		<RELATION TYPE="Elaboration" JUDGE="Lucía"/>
	</R>
	<R SDID="D1_C6_Folha.txt.seg" SSENT="5" TDID="D3_C6_JB.txt.seg" TSENT="7">
		<RELATION TYPE="Elaboration" JUDGE="Lucía"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="11" TDID="D1_C6_Folha.txt.seg" TSENT="8">
		<RELATION TYPE="Subsumption" JUDGE="Lucía"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="1" TDID="D2_C6_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Subsumption" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="1" TDID="D3_C6_JB.txt.seg" TSENT="7">
		<RELATION TYPE="Indirect-speech" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="1" TDID="D3_C6_JB.txt.seg" TSENT="7">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="2" TDID="D3_C6_JB.txt.seg" TSENT="3">
		<RELATION TYPE="Subsumption" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="5" TDID="D2_C6_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="7" TDID="D2_C6_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="2" TDID="D3_C6_JB.txt.seg" TSENT="9">
		<RELATION TYPE="Subsumption" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="10" TDID="D2_C6_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="5" TDID="D2_C6_Estadao.txt.seg" TSENT="3">
		<RELATION TYPE="Attribution" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="5" TDID="D2_C6_Estadao.txt.seg" TSENT="3">
		<RELATION TYPE="Indirect-speech" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="3" TDID="D3_C6_JB.txt.seg" TSENT="5">
		<RELATION TYPE="Subsumption" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="3" TDID="D3_C6_JB.txt.seg" TSENT="6">
		<RELATION TYPE="Subsumption" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="6" TDID="D2_C6_Estadao.txt.seg" TSENT="3">
		<RELATION TYPE="Indirect-speech" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="11" TDID="D2_C6_Estadao.txt.seg" TSENT="4">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="5" TDID="D3_C6_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="8" TDID="D3_C6_JB.txt.seg" TSENT="4">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="8" TDID="D3_C6_JB.txt.seg" TSENT="4">
		<RELATION TYPE="Attribution" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="8" TDID="D3_C6_JB.txt.seg" TSENT="12">
		<RELATION TYPE="Subsumption" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C6_JB.txt.seg" SSENT="8" TDID="D2_C6_Estadao.txt.seg" TSENT="9">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C6_Estadao.txt.seg" SSENT="14" TDID="D3_C6_JB.txt.seg" TSENT="5">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
</Anotation>
