<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Anotacao [
<!ELEMENT Anotation ( R+ ) >

<!ELEMENT R ( RELATION ) >
<!ATTLIST R SDID ( D2_C40_Estadao.txt.seg | D3_C40_OGlobo.txt.seg | D4_C40_JB.txt.seg ) #REQUIRED >
<!ATTLIST R SSENT NMTOKEN #REQUIRED >
<!ATTLIST R TDID ( D2_C40_Estadao.txt.seg | D3_C40_OGlobo.txt.seg | D4_C40_JB.txt.seg ) #REQUIRED >
<!ATTLIST R TSENT NMTOKEN #REQUIRED >

<!ELEMENT RELATION EMPTY >
<!ATTLIST RELATION JUDGE ( Erick | Lucia | thiago ) #REQUIRED >
<!ATTLIST RELATION TYPE ( Elaboration | Follow-up | Indirect-speech | Overlap | Subsumption ) #REQUIRED >

] >
<Anotation>
	<R SDID="D2_C40_Estadao.txt.seg" SSENT="1" TDID="D3_C40_OGlobo.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C40_Estadao.txt.seg" SSENT="1" TDID="D3_C40_OGlobo.txt.seg" TSENT="7">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D3_C40_OGlobo.txt.seg" SSENT="8" TDID="D2_C40_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Indirect-speech" JUDGE="Erick"/>
	</R>
	<R SDID="D3_C40_OGlobo.txt.seg" SSENT="2" TDID="D2_C40_Estadao.txt.seg" TSENT="3">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D3_C40_OGlobo.txt.seg" SSENT="2" TDID="D2_C40_Estadao.txt.seg" TSENT="5">
		<RELATION TYPE="Subsumption" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C40_Estadao.txt.seg" SSENT="6" TDID="D3_C40_OGlobo.txt.seg" TSENT="8">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C40_Estadao.txt.seg" SSENT="8" TDID="D3_C40_OGlobo.txt.seg" TSENT="3">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D3_C40_OGlobo.txt.seg" SSENT="4" TDID="D2_C40_Estadao.txt.seg" TSENT="8">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C40_Estadao.txt.seg" SSENT="9" TDID="D3_C40_OGlobo.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C40_Estadao.txt.seg" SSENT="1" TDID="D4_C40_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="Lucia"/>
	</R>
	<R SDID="D4_C40_JB.txt.seg" SSENT="6" TDID="D2_C40_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C40_Estadao.txt.seg" SSENT="3" TDID="D4_C40_JB.txt.seg" TSENT="2">
		<RELATION TYPE="Elaboration" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C40_Estadao.txt.seg" SSENT="4" TDID="D4_C40_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="Lucia"/>
	</R>
	<R SDID="D3_C40_OGlobo.txt.seg" SSENT="1" TDID="D4_C40_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C40_OGlobo.txt.seg" SSENT="2" TDID="D4_C40_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C40_OGlobo.txt.seg" SSENT="7" TDID="D4_C40_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C40_OGlobo.txt.seg" SSENT="10" TDID="D4_C40_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C40_OGlobo.txt.seg" SSENT="12" TDID="D4_C40_JB.txt.seg" TSENT="4">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C40_OGlobo.txt.seg" SSENT="12" TDID="D4_C40_JB.txt.seg" TSENT="6">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
</Anotation>
