<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Anotacao [
<!ELEMENT Anotation ( R+ ) >

<!ELEMENT R ( RELATION ) >
<!ATTLIST R SDID ( D1_C16_Folha.txt.seg | D2_C16_Estadao.txt.seg | D3_C16_OGlobo.txt.seg ) #REQUIRED >
<!ATTLIST R SSENT NMTOKEN #REQUIRED >
<!ATTLIST R TDID ( D1_C16_Folha.txt.seg | D2_C16_Estadao.txt.seg | D3_C16_OGlobo.txt.seg ) #REQUIRED >
<!ATTLIST R TSENT NMTOKEN #REQUIRED >

<!ELEMENT RELATION EMPTY >
<!ATTLIST RELATION JUDGE ( Erick | Lucia_Vinícius | thiago ) #REQUIRED >
<!ATTLIST RELATION TYPE ( Contradiction | Elaboration | Equivalence | Follow-up | Overlap | Subsumption ) #REQUIRED >

] > 
<Anotation>
	<R SDID="D1_C16_Folha.txt.seg" SSENT="1" TDID="D2_C16_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Contradiction" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C16_Estadao.txt.seg" SSENT="2" TDID="D1_C16_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C16_Estadao.txt.seg" SSENT="9" TDID="D1_C16_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C16_Estadao.txt.seg" SSENT="14" TDID="D1_C16_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C16_Estadao.txt.seg" SSENT="13" TDID="D1_C16_Folha.txt.seg" TSENT="3">
		<RELATION TYPE="Subsumption" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C16_Estadao.txt.seg" SSENT="13" TDID="D1_C16_Folha.txt.seg" TSENT="4">
		<RELATION TYPE="Subsumption" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C16_Folha.txt.seg" SSENT="6" TDID="D2_C16_Estadao.txt.seg" TSENT="5">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C16_Folha.txt.seg" SSENT="8" TDID="D2_C16_Estadao.txt.seg" TSENT="3">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C16_Folha.txt.seg" SSENT="10" TDID="D2_C16_Estadao.txt.seg" TSENT="21">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C16_Folha.txt.seg" SSENT="13" TDID="D2_C16_Estadao.txt.seg" TSENT="13">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C16_Estadao.txt.seg" SSENT="2" TDID="D1_C16_Folha.txt.seg" TSENT="15">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C16_Folha.txt.seg" SSENT="15" TDID="D2_C16_Estadao.txt.seg" TSENT="9">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C16_Folha.txt.seg" SSENT="15" TDID="D2_C16_Estadao.txt.seg" TSENT="12">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C16_Estadao.txt.seg" SSENT="14" TDID="D1_C16_Folha.txt.seg" TSENT="15">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C16_Estadao.txt.seg" SSENT="17" TDID="D1_C16_Folha.txt.seg" TSENT="15">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C16_Folha.txt.seg" SSENT="1" TDID="D3_C16_OGlobo.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="Lucia_Vinícius"/>
	</R>
	<R SDID="D1_C16_Folha.txt.seg" SSENT="3" TDID="D3_C16_OGlobo.txt.seg" TSENT="2">
		<RELATION TYPE="Equivalence" JUDGE="Lucia_Vinícius"/>
	</R>
	<R SDID="D1_C16_Folha.txt.seg" SSENT="6" TDID="D3_C16_OGlobo.txt.seg" TSENT="5">
		<RELATION TYPE="Overlap" JUDGE="Lucia_Vinícius"/>
	</R>
	<R SDID="D1_C16_Folha.txt.seg" SSENT="7" TDID="D3_C16_OGlobo.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinícius"/>
	</R>
	<R SDID="D3_C16_OGlobo.txt.seg" SSENT="3" TDID="D1_C16_Folha.txt.seg" TSENT="7">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinícius"/>
	</R>
	<R SDID="D1_C16_Folha.txt.seg" SSENT="8" TDID="D3_C16_OGlobo.txt.seg" TSENT="4">
		<RELATION TYPE="Overlap" JUDGE="Lucia_Vinícius"/>
	</R>
	<R SDID="D1_C16_Folha.txt.seg" SSENT="13" TDID="D3_C16_OGlobo.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinícius"/>
	</R>
	<R SDID="D1_C16_Folha.txt.seg" SSENT="15" TDID="D3_C16_OGlobo.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinícius"/>
	</R>
	<R SDID="D1_C16_Folha.txt.seg" SSENT="15" TDID="D3_C16_OGlobo.txt.seg" TSENT="3">
		<RELATION TYPE="Overlap" JUDGE="Lucia_Vinícius"/>
	</R>
	<R SDID="D2_C16_Estadao.txt.seg" SSENT="1" TDID="D3_C16_OGlobo.txt.seg" TSENT="1">
		<RELATION TYPE="Contradiction" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C16_Estadao.txt.seg" SSENT="1" TDID="D3_C16_OGlobo.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C16_Estadao.txt.seg" SSENT="3" TDID="D3_C16_OGlobo.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C16_Estadao.txt.seg" SSENT="3" TDID="D3_C16_OGlobo.txt.seg" TSENT="4">
		<RELATION TYPE="Subsumption" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C16_Estadao.txt.seg" SSENT="5" TDID="D3_C16_OGlobo.txt.seg" TSENT="5">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C16_Estadao.txt.seg" SSENT="11" TDID="D3_C16_OGlobo.txt.seg" TSENT="3">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C16_Estadao.txt.seg" SSENT="13" TDID="D3_C16_OGlobo.txt.seg" TSENT="2">
		<RELATION TYPE="Subsumption" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C16_Estadao.txt.seg" SSENT="20" TDID="D3_C16_OGlobo.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
</Anotation>
