<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Anotacao [
<!ELEMENT Anotation ( R+ ) >

<!ELEMENT R ( RELATION ) >
<!ATTLIST R SDID ( D1_C8_Estadao.txt.seg | D2_C8_OGlobo.txt.seg | D3_C8_JB.txt.seg ) #REQUIRED >
<!ATTLIST R SSENT ( 1 | 10 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 ) #REQUIRED >
<!ATTLIST R TDID ( D1_C8_Estadao.txt.seg | D2_C8_OGlobo.txt.seg | D3_C8_JB.txt.seg ) #REQUIRED >
<!ATTLIST R TSENT ( 1 | 10 | 2 | 3 | 4 | 5 | 7 | 8 | 9 ) #REQUIRED >

<!ELEMENT RELATION EMPTY >
<!ATTLIST RELATION JUDGE ( Erick | Lucia_Vinicius | thiago ) #REQUIRED >
<!ATTLIST RELATION TYPE ( Elaboration | Follow-up | Historical-background | Overlap | Subsumption ) #REQUIRED >

] >

<Anotation>
	<R SDID="D1_C8_Estadao.txt.seg" SSENT="1" TDID="D2_C8_OGlobo.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C8_Estadao.txt.seg" SSENT="1" TDID="D2_C8_OGlobo.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C8_OGlobo.txt.seg" SSENT="5" TDID="D1_C8_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Historical-background" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C8_Estadao.txt.seg" SSENT="2" TDID="D2_C8_OGlobo.txt.seg" TSENT="4">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C8_Estadao.txt.seg" SSENT="7" TDID="D2_C8_OGlobo.txt.seg" TSENT="3">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C8_Estadao.txt.seg" SSENT="8" TDID="D2_C8_OGlobo.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C8_OGlobo.txt.seg" SSENT="5" TDID="D1_C8_Estadao.txt.seg" TSENT="8">
		<RELATION TYPE="Historical-background" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C8_OGlobo.txt.seg" SSENT="4" TDID="D1_C8_Estadao.txt.seg" TSENT="9">
		<RELATION TYPE="Subsumption" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C8_Estadao.txt.seg" SSENT="1" TDID="D3_C8_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D3_C8_JB.txt.seg" SSENT="6" TDID="D1_C8_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D3_C8_JB.txt.seg" SSENT="8" TDID="D1_C8_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D3_C8_JB.txt.seg" SSENT="10" TDID="D1_C8_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D3_C8_JB.txt.seg" SSENT="3" TDID="D1_C8_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Subsumption" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C8_Estadao.txt.seg" SSENT="5" TDID="D3_C8_JB.txt.seg" TSENT="5">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D3_C8_JB.txt.seg" SSENT="8" TDID="D1_C8_Estadao.txt.seg" TSENT="5">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D3_C8_JB.txt.seg" SSENT="8" TDID="D1_C8_Estadao.txt.seg" TSENT="5">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C8_Estadao.txt.seg" SSENT="6" TDID="D3_C8_JB.txt.seg" TSENT="7">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C8_Estadao.txt.seg" SSENT="6" TDID="D3_C8_JB.txt.seg" TSENT="9">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C8_Estadao.txt.seg" SSENT="7" TDID="D3_C8_JB.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C8_Estadao.txt.seg" SSENT="7" TDID="D3_C8_JB.txt.seg" TSENT="5">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C8_Estadao.txt.seg" SSENT="7" TDID="D3_C8_JB.txt.seg" TSENT="10">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C8_Estadao.txt.seg" SSENT="8" TDID="D3_C8_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C8_Estadao.txt.seg" SSENT="8" TDID="D3_C8_JB.txt.seg" TSENT="4">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C8_Estadao.txt.seg" SSENT="9" TDID="D3_C8_JB.txt.seg" TSENT="4">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C8_Estadao.txt.seg" SSENT="4" TDID="D3_C8_JB.txt.seg" TSENT="3">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D2_C8_OGlobo.txt.seg" SSENT="1" TDID="D3_C8_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C8_JB.txt.seg" SSENT="10" TDID="D2_C8_OGlobo.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C8_OGlobo.txt.seg" SSENT="2" TDID="D3_C8_JB.txt.seg" TSENT="3">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C8_OGlobo.txt.seg" SSENT="3" TDID="D3_C8_JB.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C8_OGlobo.txt.seg" SSENT="4" TDID="D3_C8_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C8_JB.txt.seg" SSENT="3" TDID="D2_C8_OGlobo.txt.seg" TSENT="4">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C8_OGlobo.txt.seg" SSENT="4" TDID="D3_C8_JB.txt.seg" TSENT="4">
		<RELATION TYPE="Subsumption" JUDGE="thiago"/>
	</R>
</Anotation>
