<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Anotacao [
<!ELEMENT Anotation ( R+ ) >

<!ELEMENT R ( RELATION ) >
<!ATTLIST R SDID ( D1_C20_Folha.txt.seg | D4_C20_JB.txt.seg | D5_C20_GPovo.txt.seg ) #REQUIRED >
<!ATTLIST R SSENT NMTOKEN #REQUIRED >
<!ATTLIST R TDID ( D1_C20_Folha.txt.seg | D4_C20_JB.txt.seg | D5_C20_GPovo.txt.seg ) #REQUIRED >
<!ATTLIST R TSENT NMTOKEN #REQUIRED >

<!ELEMENT RELATION EMPTY >
<!ATTLIST RELATION JUDGE ( Erick | Lucia | thiago ) #REQUIRED >
<!ATTLIST RELATION TYPE ( Elaboration | Follow-up | Overlap | Subsumption ) #REQUIRED >
] >
<Anotation>
	<R SDID="D4_C20_JB.txt.seg" SSENT="1" TDID="D1_C20_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C20_Folha.txt.seg" SSENT="3" TDID="D4_C20_JB.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C20_Folha.txt.seg" SSENT="4" TDID="D4_C20_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C20_Folha.txt.seg" SSENT="4" TDID="D4_C20_JB.txt.seg" TSENT="3">
		<RELATION TYPE="Subsumption" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C20_Folha.txt.seg" SSENT="10" TDID="D4_C20_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C20_Folha.txt.seg" SSENT="1" TDID="D5_C20_GPovo.txt.seg" TSENT="7">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C20_Folha.txt.seg" SSENT="1" TDID="D5_C20_GPovo.txt.seg" TSENT="19">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D5_C20_GPovo.txt.seg" SSENT="1" TDID="D1_C20_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C20_Folha.txt.seg" SSENT="2" TDID="D5_C20_GPovo.txt.seg" TSENT="5">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C20_Folha.txt.seg" SSENT="2" TDID="D5_C20_GPovo.txt.seg" TSENT="6">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C20_Folha.txt.seg" SSENT="3" TDID="D5_C20_GPovo.txt.seg" TSENT="10">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C20_Folha.txt.seg" SSENT="6" TDID="D5_C20_GPovo.txt.seg" TSENT="18">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D5_C20_GPovo.txt.seg" SSENT="6" TDID="D1_C20_Folha.txt.seg" TSENT="11">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C20_Folha.txt.seg" SSENT="12" TDID="D5_C20_GPovo.txt.seg" TSENT="7">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C20_Folha.txt.seg" SSENT="12" TDID="D5_C20_GPovo.txt.seg" TSENT="12">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C20_Folha.txt.seg" SSENT="14" TDID="D5_C20_GPovo.txt.seg" TSENT="8">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C20_Folha.txt.seg" SSENT="15" TDID="D5_C20_GPovo.txt.seg" TSENT="8">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D5_C20_GPovo.txt.seg" SSENT="18" TDID="D1_C20_Folha.txt.seg" TSENT="15">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D5_C20_GPovo.txt.seg" SSENT="19" TDID="D1_C20_Folha.txt.seg" TSENT="15">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C20_Folha.txt.seg" SSENT="16" TDID="D5_C20_GPovo.txt.seg" TSENT="9">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D5_C20_GPovo.txt.seg" SSENT="5" TDID="D1_C20_Folha.txt.seg" TSENT="17">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C20_Folha.txt.seg" SSENT="18" TDID="D5_C20_GPovo.txt.seg" TSENT="3">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D4_C20_JB.txt.seg" SSENT="1" TDID="D5_C20_GPovo.txt.seg" TSENT="10">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D4_C20_JB.txt.seg" SSENT="2" TDID="D5_C20_GPovo.txt.seg" TSENT="10">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D4_C20_JB.txt.seg" SSENT="1" TDID="D5_C20_GPovo.txt.seg" TSENT="14">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D4_C20_JB.txt.seg" SSENT="2" TDID="D5_C20_GPovo.txt.seg" TSENT="14">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D4_C20_JB.txt.seg" SSENT="3" TDID="D5_C20_GPovo.txt.seg" TSENT="14">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
</Anotation>
