<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Anotacao [
<!ELEMENT Anotation ( R+ ) >

<!ELEMENT R ( RELATION ) >
<!ATTLIST R SDID ( D1_C1_Folha.txt.seg | D2_C1_Estadao.txt.seg | D3_C1_JB.txt.seg ) #REQUIRED >
<!ATTLIST R SSENT ( 1 | 2 | 3 | 4 | 5 | 6 | 7 ) #REQUIRED >
<!ATTLIST R TDID ( D1_C1_Folha.txt.seg | D2_C1_Estadao.txt.seg | D3_C1_JB.txt.seg ) #REQUIRED >
<!ATTLIST R TSENT ( 1 | 2 | 3 | 4 | 5 | 6 | 7 ) #REQUIRED >

<!ELEMENT RELATION EMPTY >
<!ATTLIST RELATION JUDGE ( Erick | Lucia | thiago ) #REQUIRED >
<!ATTLIST RELATION TYPE ( Attribution | Contradiction | Elaboration | Equivalence | Follow-up | Historical-background | Identity | Overlap | Subsumption ) #REQUIRED >

] > 

<Anotation>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="1" TDID="D1_C1_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Subsumption" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="3" TDID="D1_C1_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="7" TDID="D1_C1_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C1_Folha.txt.seg" SSENT="2" TDID="D2_C1_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C1_Folha.txt.seg" SSENT="2" TDID="D2_C1_Estadao.txt.seg" TSENT="3">
		<RELATION TYPE="Attribution" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C1_Folha.txt.seg" SSENT="2" TDID="D2_C1_Estadao.txt.seg" TSENT="3">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="4" TDID="D1_C1_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="5" TDID="D1_C1_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="7" TDID="D1_C1_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C1_Folha.txt.seg" SSENT="3" TDID="D2_C1_Estadao.txt.seg" TSENT="3">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C1_Folha.txt.seg" SSENT="4" TDID="D2_C1_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Historical-background" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C1_Folha.txt.seg" SSENT="5" TDID="D2_C1_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Subsumption" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="3" TDID="D1_C1_Folha.txt.seg" TSENT="5">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C1_Folha.txt.seg" SSENT="5" TDID="D2_C1_Estadao.txt.seg" TSENT="7">
		<RELATION TYPE="Contradiction" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="7" TDID="D1_C1_Folha.txt.seg" TSENT="5">
		<RELATION TYPE="Elaboration" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="3" TDID="D1_C1_Folha.txt.seg" TSENT="6">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D1_C1_Folha.txt.seg" SSENT="7" TDID="D2_C1_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Historical-background" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C1_JB.txt.seg" SSENT="1" TDID="D1_C1_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Attribution" JUDGE="Lucia"/>
	</R>
	<R SDID="D3_C1_JB.txt.seg" SSENT="1" TDID="D1_C1_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Subsumption" JUDGE="Lucia"/>
	</R>
	<R SDID="D3_C1_JB.txt.seg" SSENT="4" TDID="D1_C1_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Lucia"/>
	</R>
	<R SDID="D3_C1_JB.txt.seg" SSENT="6" TDID="D1_C1_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C1_Folha.txt.seg" SSENT="2" TDID="D3_C1_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Lucia"/>
	</R>
	<R SDID="D3_C1_JB.txt.seg" SSENT="3" TDID="D1_C1_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Elaboration" JUDGE="Lucia"/>
	</R>
	<R SDID="D3_C1_JB.txt.seg" SSENT="4" TDID="D1_C1_Folha.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C1_Folha.txt.seg" SSENT="2" TDID="D3_C1_JB.txt.seg" TSENT="6">
		<RELATION TYPE="Overlap" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C1_Folha.txt.seg" SSENT="3" TDID="D3_C1_JB.txt.seg" TSENT="3">
		<RELATION TYPE="Contradiction" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C1_Folha.txt.seg" SSENT="5" TDID="D3_C1_JB.txt.seg" TSENT="2">
		<RELATION TYPE="Subsumption" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C1_Folha.txt.seg" SSENT="5" TDID="D3_C1_JB.txt.seg" TSENT="4">
		<RELATION TYPE="Elaboration" JUDGE="Lucia"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="1" TDID="D3_C1_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D3_C1_JB.txt.seg" SSENT="6" TDID="D2_C1_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="2" TDID="D3_C1_JB.txt.seg" TSENT="2">
		<RELATION TYPE="Identity" JUDGE="Erick"/>
	</R>
	<R SDID="D3_C1_JB.txt.seg" SSENT="7" TDID="D2_C1_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="3" TDID="D3_C1_JB.txt.seg" TSENT="3">
		<RELATION TYPE="Equivalence" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="4" TDID="D3_C1_JB.txt.seg" TSENT="2">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="4" TDID="D3_C1_JB.txt.seg" TSENT="7">
		<RELATION TYPE="Identity" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="5" TDID="D3_C1_JB.txt.seg" TSENT="4">
		<RELATION TYPE="Identity" JUDGE="Erick"/>
	</R>
	<R SDID="D3_C1_JB.txt.seg" SSENT="5" TDID="D2_C1_Estadao.txt.seg" TSENT="5">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D3_C1_JB.txt.seg" SSENT="6" TDID="D2_C1_Estadao.txt.seg" TSENT="5">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="6" TDID="D3_C1_JB.txt.seg" TSENT="4">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="6" TDID="D3_C1_JB.txt.seg" TSENT="5">
		<RELATION TYPE="Identity" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="7" TDID="D3_C1_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="7" TDID="D3_C1_JB.txt.seg" TSENT="4">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C1_Estadao.txt.seg" SSENT="7" TDID="D3_C1_JB.txt.seg" TSENT="6">
		<RELATION TYPE="Identity" JUDGE="Erick"/>
	</R>
</Anotation>
