<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Anotacao [
<!ELEMENT Anotation ( R+ ) >

<!ELEMENT R ( RELATION ) >
<!ATTLIST R SDID ( D1_C43_Folha.txt.seg | D2_C43_Estadao.txt.seg | D4_C43_JB.txt.seg ) #REQUIRED >
<!ATTLIST R SSENT NMTOKEN #REQUIRED >
<!ATTLIST R TDID ( D1_C43_Folha.txt.seg | D2_C43_Estadao.txt.seg | D4_C43_JB.txt.seg ) #REQUIRED >
<!ATTLIST R TSENT NMTOKEN #REQUIRED >

<!ELEMENT RELATION EMPTY >
<!ATTLIST RELATION JUDGE ( Erick | Lucia | thiago ) #REQUIRED >
<!ATTLIST RELATION TYPE ( Contradiction | Elaboration | Follow-up | Overlap ) #REQUIRED >
] > 
<Anotation>
	<R SDID="D1_C43_Folha.txt.seg" SSENT="1" TDID="D2_C43_Estadao.txt.seg" TSENT="1">
		<RELATION TYPE="Follow-up" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C43_Folha.txt.seg" SSENT="1" TDID="D2_C43_Estadao.txt.seg" TSENT="6">
		<RELATION TYPE="Follow-up" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C43_Folha.txt.seg" SSENT="3" TDID="D2_C43_Estadao.txt.seg" TSENT="10">
		<RELATION TYPE="Follow-up" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C43_Folha.txt.seg" SSENT="7" TDID="D2_C43_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C43_Folha.txt.seg" SSENT="11" TDID="D2_C43_Estadao.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C43_Folha.txt.seg" SSENT="16" TDID="D2_C43_Estadao.txt.seg" TSENT="7">
		<RELATION TYPE="Elaboration" JUDGE="Lucia"/>
	</R>
	<R SDID="D1_C43_Folha.txt.seg" SSENT="3" TDID="D4_C43_JB.txt.seg" TSENT="4">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C43_Folha.txt.seg" SSENT="8" TDID="D4_C43_JB.txt.seg" TSENT="4">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D4_C43_JB.txt.seg" SSENT="5" TDID="D1_C43_Folha.txt.seg" TSENT="8">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C43_Folha.txt.seg" SSENT="11" TDID="D4_C43_JB.txt.seg" TSENT="17">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C43_Folha.txt.seg" SSENT="16" TDID="D4_C43_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C43_Folha.txt.seg" SSENT="16" TDID="D4_C43_JB.txt.seg" TSENT="2">
		<RELATION TYPE="Contradiction" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C43_Folha.txt.seg" SSENT="16" TDID="D4_C43_JB.txt.seg" TSENT="17">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C43_Folha.txt.seg" SSENT="17" TDID="D4_C43_JB.txt.seg" TSENT="2">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D2_C43_Estadao.txt.seg" SSENT="2" TDID="D4_C43_JB.txt.seg" TSENT="17">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C43_Estadao.txt.seg" SSENT="2" TDID="D4_C43_JB.txt.seg" TSENT="18">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D2_C43_Estadao.txt.seg" SSENT="4" TDID="D4_C43_JB.txt.seg" TSENT="20">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
	<R SDID="D4_C43_JB.txt.seg" SSENT="5" TDID="D2_C43_Estadao.txt.seg" TSENT="10">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
</Anotation>
