<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Anotacao [
<!ELEMENT Anotation ( R+ ) >

<!ELEMENT R ( RELATION ) >
<!ATTLIST R SDID ( D1_C36_Folha.txt.seg | D3_C36_OGlobo.txt.seg | D4_C36_JB.txt.seg ) #REQUIRED >
<!ATTLIST R SSENT NMTOKEN #REQUIRED >
<!ATTLIST R TDID ( D1_C36_Folha.txt.seg | D3_C36_OGlobo.txt.seg | D4_C36_JB.txt.seg ) #REQUIRED >
<!ATTLIST R TSENT NMTOKEN #REQUIRED >

<!ELEMENT RELATION EMPTY >
<!ATTLIST RELATION JUDGE ( Erick | Lucia_Vinicius | thiago ) #REQUIRED >
<!ATTLIST RELATION TYPE ( Attribution | Contradiction | Elaboration | Equivalence | Follow-up | Historical-background | Overlap | Subsumption ) #REQUIRED >
] > 
<Anotation>
	<R SDID="D1_C36_Folha.txt.seg" SSENT="1" TDID="D3_C36_OGlobo.txt.seg" TSENT="1">
		<RELATION TYPE="Subsumption" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D3_C36_OGlobo.txt.seg" SSENT="2" TDID="D1_C36_Folha.txt.seg" TSENT="1">
		<RELATION TYPE="Attribution" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C36_Folha.txt.seg" SSENT="1" TDID="D3_C36_OGlobo.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C36_Folha.txt.seg" SSENT="2" TDID="D3_C36_OGlobo.txt.seg" TSENT="3">
		<RELATION TYPE="Subsumption" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D3_C36_OGlobo.txt.seg" SSENT="6" TDID="D1_C36_Folha.txt.seg" TSENT="3">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D3_C36_OGlobo.txt.seg" SSENT="8" TDID="D1_C36_Folha.txt.seg" TSENT="3">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D3_C36_OGlobo.txt.seg" SSENT="5" TDID="D1_C36_Folha.txt.seg" TSENT="4">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D3_C36_OGlobo.txt.seg" SSENT="7" TDID="D1_C36_Folha.txt.seg" TSENT="4">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D3_C36_OGlobo.txt.seg" SSENT="10" TDID="D1_C36_Folha.txt.seg" TSENT="10">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D3_C36_OGlobo.txt.seg" SSENT="3" TDID="D1_C36_Folha.txt.seg" TSENT="13">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C36_Folha.txt.seg" SSENT="13" TDID="D3_C36_OGlobo.txt.seg" TSENT="16">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D3_C36_OGlobo.txt.seg" SSENT="2" TDID="D1_C36_Folha.txt.seg" TSENT="15">
		<RELATION TYPE="Follow-up" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C36_Folha.txt.seg" SSENT="15" TDID="D3_C36_OGlobo.txt.seg" TSENT="16">
		<RELATION TYPE="Elaboration" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D3_C36_OGlobo.txt.seg" SSENT="18" TDID="D1_C36_Folha.txt.seg" TSENT="15">
		<RELATION TYPE="Subsumption" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C36_Folha.txt.seg" SSENT="16" TDID="D3_C36_OGlobo.txt.seg" TSENT="19">
		<RELATION TYPE="Equivalence" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C36_Folha.txt.seg" SSENT="17" TDID="D3_C36_OGlobo.txt.seg" TSENT="20">
		<RELATION TYPE="Equivalence" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C36_Folha.txt.seg" SSENT="18" TDID="D3_C36_OGlobo.txt.seg" TSENT="2">
		<RELATION TYPE="Historical-background" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C36_Folha.txt.seg" SSENT="18" TDID="D3_C36_OGlobo.txt.seg" TSENT="12">
		<RELATION TYPE="Overlap" JUDGE="Lucia_Vinicius"/>
	</R>
	<R SDID="D1_C36_Folha.txt.seg" SSENT="1" TDID="D4_C36_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C36_Folha.txt.seg" SSENT="2" TDID="D4_C36_JB.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C36_Folha.txt.seg" SSENT="11" TDID="D4_C36_JB.txt.seg" TSENT="10">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D4_C36_JB.txt.seg" SSENT="19" TDID="D1_C36_Folha.txt.seg" TSENT="12">
		<RELATION TYPE="Elaboration" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C36_Folha.txt.seg" SSENT="12" TDID="D4_C36_JB.txt.seg" TSENT="20">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D4_C36_JB.txt.seg" SSENT="1" TDID="D1_C36_Folha.txt.seg" TSENT="15">
		<RELATION TYPE="Follow-up" JUDGE="Erick"/>
	</R>
	<R SDID="D1_C36_Folha.txt.seg" SSENT="18" TDID="D4_C36_JB.txt.seg" TSENT="21">
		<RELATION TYPE="Overlap" JUDGE="Erick"/>
	</R>
	<R SDID="D3_C36_OGlobo.txt.seg" SSENT="1" TDID="D4_C36_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C36_OGlobo.txt.seg" SSENT="2" TDID="D4_C36_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C36_OGlobo.txt.seg" SSENT="2" TDID="D4_C36_JB.txt.seg" TSENT="1">
		<RELATION TYPE="Attribution" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C36_OGlobo.txt.seg" SSENT="3" TDID="D4_C36_JB.txt.seg" TSENT="2">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C36_OGlobo.txt.seg" SSENT="10" TDID="D4_C36_JB.txt.seg" TSENT="3">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C36_OGlobo.txt.seg" SSENT="12" TDID="D4_C36_JB.txt.seg" TSENT="21">
		<RELATION TYPE="Overlap" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C36_OGlobo.txt.seg" SSENT="12" TDID="D4_C36_JB.txt.seg" TSENT="21">
		<RELATION TYPE="Contradiction" JUDGE="thiago"/>
	</R>
	<R SDID="D3_C36_OGlobo.txt.seg" SSENT="13" TDID="D4_C36_JB.txt.seg" TSENT="3">
		<RELATION TYPE="Follow-up" JUDGE="thiago"/>
	</R>
</Anotation>
